const INS_NONE = 0x00;
const INS_RESET = 0x02;

const INS_GET_KEY = 0x20;
const INS_PUT_KEY = 0x22;
const INS_GET_CHACHA8_PREKEY = 0x24;
const INS_VERIFY_KEY = 0x26;

const INS_SECRET_KEY_TO_PUBLIC_KEY = 0x30;
const INS_GEN_KEY_DERIVATION = 0x32;
const INS_DERIVATION_TO_SCALAR = 0x34;
const INS_DERIVE_PUBLIC_KEY = 0x36;
const INS_DERIVE_SECRET_KEY = 0x38;
const INS_GEN_KEY_IMAGE = 0x3a;
const INS_SECRET_KEY_ADD = 0x3c;
const INS_SECRET_KEY_SUB = 0x3e;

const INS_GENERATE_KEYPAIR = 0x40;
const INS_SECRET_SCAL_MUL_KEY = 0x42;
const INS_SECRET_SCAL_MUL_BASE = 0x44;

const INS_DERIVE_SUBADDRESS_PUBLIC_KEY = 0x46;
const INS_GET_SUBADDRESS = 0x48;
const INS_GET_SUBADDRESS_SPEND_PUBLIC_KEY = 0x4a;
const INS_GET_SUBADDRESS_SECRET_KEY = 0x4c;

const INS_OPEN_TX = 0x70;
const INS_SET_SIGNATURE_MODE = 0x72;
const INS_GET_ADDITIONAL_KEY = 0x74;
const INS_STEALTH = 0x76;
const INS_BLIND = 0x78;
const INS_UNBLIND = 0x7a;
const INS_VALIDATE = 0x7c;
const INS_MLSAG = 0x7e;
const INS_CLOSE_TX = 0x80;

const INS_GET_RESPONSE = 0xc0;
